#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'dmg'
cookbook 'homebrew'
cookbook 'homesick'
cookbook 'mac_os_x'
cookbook 'pivotal_workstation',
  :git => 'https://github.com/patcon/pivotal_workstation.git',
  :ref => 'dmg-cookbook'
cookbook 'platform_packages'
cookbook 'zip_app'
